set_property SRC_FILE_INFO {cfile:C:/Users/Admin/Documents/MIPS_single_cycle/temp_MIPS.srcs/constrs_1/imports/HDL_verilog/Arty-Z7-20-Master.xdc rfile:../../../temp_MIPS.srcs/constrs_1/imports/HDL_verilog/Arty-Z7-20-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H16 [get_ports i_clk]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M19 [get_ports i_arst]
