# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Asus/Desktop/TKLL_2024/MIPS_single_cycle/new_prj/new_prj.srcs/sources_1/bd/zynq_example/ip/zynq_example_blk_mem_gen_0_0/zynq_example_blk_mem_gen_0_0.xci
# IP: The module: 'zynq_example_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Asus/Desktop/TKLL_2024/MIPS_single_cycle/new_prj/new_prj.gen/sources_1/bd/zynq_example/ip/zynq_example_blk_mem_gen_0_0/zynq_example_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_example_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Asus/Desktop/TKLL_2024/MIPS_single_cycle/new_prj/new_prj.srcs/sources_1/bd/zynq_example/ip/zynq_example_blk_mem_gen_0_0/zynq_example_blk_mem_gen_0_0.xci
# IP: The module: 'zynq_example_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Asus/Desktop/TKLL_2024/MIPS_single_cycle/new_prj/new_prj.gen/sources_1/bd/zynq_example/ip/zynq_example_blk_mem_gen_0_0/zynq_example_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_example_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
